site_name: TopOMetry Documentation
nav:
    - Welcome!: index.md
    - Installation: installation.md
    - Quick-start: quickstart.md
    - Single-cell analysis: TopOMetry_Intro_pbmc_3k.md
    - The TopOGraph model: topograph.md
    - Diffusion harmonics: diffusor.md
theme:
    logo: img/logo.png
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - bash

plugins:
- search
- mkdocstrings
